# -*- coding: utf-8 -*-
"""parse_skills.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JlvCyMRpzessAXItK_iS_Hop7Ggd-6Fs
"""

import pandas as pd  
import numpy as np
import matplotlib.pyplot as plt

"""BU PROGRAMDA AMAC YAN YANA OLAN YETENEKLERI AKT ALTA KENDI ETIKETIYLE SIRALAMAK"""

data=pd.read_csv("/content/cleaned_deneme2_skills.csv")
data.head()

#burada kullanmadigimiz ozellikleri siliyoruz
data.drop(['genel_nit_is_tanimi','ilan_baslik'], axis=1,inplace=True)
data.head()

#yetenek ve etiket bilgisi icin iki dizi olusturuyoruz
skills=[]
s_label = []

for i in range(0,len(data)):
  label = data['label'][i]
  text = data['skills'][i]
  #burada her yetenek satirini virgul virgul ayiriyoruz
  x = text.split(',')
  for xe in x:
     #ayrilan yetenekleri skills'e ekliyoruz ve her yetenek icin etiket bilgisini ekliyoruz
    skills.append(xe)
    s_label.append(label)


#yetenek ve etiket bilgisinden olusan bir veriseti olusturuyoruz
clean_df = pd.DataFrame(skills,columns=['skill'])
clean_df['label'] = s_label
clean_df.to_csv('skill_data.csv',encoding='utf-8')
clean_df.head()

